# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mealist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #pod 'Alamofire', '4.0.0'
  pod 'RealmSwift', '2.4.3'
  pod 'RxSwift', '3.6.1'

  target 'mealistTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mealistUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
